# Usa uma versão leve do Python
FROM python:3.11-slim

# Define a pasta de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo de requisitos e instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o resto do código do seu back-end
COPY . .

# Expõe a porta que o Cloud Run exige (8080)
EXPOSE 8080

# Comando para iniciar o servidor (IMPORTANTE: Mude 'meu_projeto' para o nome da pasta onde está o seu settings.py)
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "meu_projeto.wsgi:application"]