# Generated by Django 6.0.7 on 2026-07-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpinista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('nomePai', models.CharField(blank=True, max_length=255, null=True)),
                ('telefonePai', models.CharField(blank=True, max_length=20, null=True)),
                ('nomeMae', models.CharField(blank=True, max_length=255, null=True)),
                ('telefoneMae', models.CharField(blank=True, max_length=20, null=True)),
                ('restricaoSaude', models.CharField(blank=True, max_length=255, null=True)),
                ('medicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('conheciaEscalada', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Inativo', 'Inativo')], default='Pendente', max_length=20)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataInicio', models.DateField()),
                ('datFim', models.DateField()),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataEvento', models.DateField()),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('ENCONTRISTA', 'Encontrista'), ('EQUIPE', 'Equipe'), ('PALESTRANTE', 'Palestrante')], max_length=50)),
                ('corGrupo', models.CharField(blank=True, max_length=50, null=True)),
                ('alpinista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros', to='core.alpinista')),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.encontro')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpinista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.alpinista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.evento')),
            ],
        ),
    ]
