# Generated by Django 6.0.7 on 2026-07-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encontro',
            old_name='datFim',
            new_name='dataFim',
        ),
    ]
