# Generated by Django 5.2.16 on 2026-07-17 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_datfim_encontro_datafim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encontro",
            name="dataFim",
        ),
        migrations.RemoveField(
            model_name="encontro",
            name="dataInicio",
        ),
        migrations.RemoveField(
            model_name="encontro",
            name="nome",
        ),
        migrations.AddField(
            model_name="encontro",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 7, 17, 2, 8, 52, 868078, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encontro",
            name="data_encontro",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 7, 17, 2, 9, 7, 188549, tzinfo=datetime.timezone.utc
                ),
                help_text="Data do encontro",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encontro",
            name="encontro",
            field=models.CharField(
                default=datetime.datetime(
                    2026, 7, 17, 2, 9, 24, 286764, tzinfo=datetime.timezone.utc
                ),
                help_text="Ex: Escalada 1 / AVC / Esppa",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encontro",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_agendamento", "Em Agendamento"),
                    ("agendado", "Agendado"),
                ],
                default="em_agendamento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alpinista",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="alpinista",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "ativo"),
                    ("pendente", "pendente"),
                    ("inativo", "inativo"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="encontro",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="encontro",
            name="local",
            field=models.CharField(default="Nova Betânia", max_length=255),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="participacaoencontro",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="participacaoevento",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
