# Generated by Django 5.2.16 on 2026-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_encontro_datafim_remove_encontro_datainicio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encontro",
            name="criado_em",
            field=models.DateField(auto_now_add=True),
        ),
    ]
