# Generated by Django 5.2.16 on 2026-07-20 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_encontro_criado_em"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encontro",
            name="data_encontro",
        ),
        migrations.AddField(
            model_name="encontro",
            name="data_exato",
            field=models.CharField(
                default=datetime.datetime(
                    2026, 7, 20, 20, 13, 7, 100947, tzinfo=datetime.timezone.utc
                ),
                help_text="Ex: 19, 24, 25, 26 de Julho de XXXX",
                max_length=150,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encontro",
            name="data_referencia",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 7, 20, 20, 13, 17, 53035, tzinfo=datetime.timezone.utc
                ),
                help_text="O 1º dia do encontro",
            ),
            preserve_default=False,
        ),
    ]
