# Generated by Django 5.2.16 on 2026-07-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_encontro_data_encontro_encontro_data_exato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncaoEncontro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Dirigente, Palestrante", max_length=100
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("encontrista", "Encontrista"),
                            ("equipe", "Equipe de trabalho"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "descricao_faq",
                    models.TextField(
                        blank=True,
                        help_text="Explicacao do que a equipe faz (usado na tela de FAQ)",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="encontro",
            name="participantes",
            field=models.ManyToManyField(
                blank=True,
                related_name="encontro_participacao",
                through="core.ParticipacaoEncontro",
                to="core.alpinista",
            ),
        ),
        migrations.AlterField(
            model_name="participacaoencontro",
            name="alpinista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participacoes_encontros",
                to="core.alpinista",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participacaoencontro",
            unique_together={("alpinista", "encontro")},
        ),
        migrations.AlterField(
            model_name="participacaoencontro",
            name="funcao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.funcaoencontro"
            ),
        ),
    ]
