# Generated by Django 5.2.16 on 2026-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_participacaoencontro_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontro',
            name='tipo',
            field=models.CharField(choices=[('Escalada', 'Escalada'), ('AVC', 'AVC'), ('Esppa', 'Esppa'), ('Acampamento', 'Acampamento')], default='Escalada', max_length=20),
        ),
    ]
