# Generated by Django 5.2.16 on 2026-08-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_logsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpinista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
