# Generated by Django 5.2.16 on 2026-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_alpinista_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpinista',
            name='is_neurodivergente',
            field=models.BooleanField(default=False, verbose_name='É neurodivergente?'),
        ),
        migrations.AddField(
            model_name='alpinista',
            name='tipo_neurodivergente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Neurodivergencia'),
        ),
    ]
