# Generated by Django 5.2.16 on 2026-08-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alpinista_is_neurodivergente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpinista',
            name='cpf',
            field=models.CharField(default=False, max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
