# Generated by Django 5.2.16 on 2026-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alpinista_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='dataEvento',
            new_name='data_evento',
        ),
        migrations.RenameField(
            model_name='participacaoencontro',
            old_name='corGrupo',
            new_name='cor_grupo',
        ),
        migrations.AlterField(
            model_name='encontro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
