# Generated by Django 5.2.16 on 2026-09-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_dataevento_evento_data_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpinista',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('pendente', 'pendente'), ('confirmado', 'confirmado'), ('inativo', 'inativo')], default='Pendente', max_length=20),
        ),
    ]
