# Generated by Django 5.2.16 on 2026-09-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_alpinista_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcaoencontro',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='funcaoencontro',
            name='ordem',
            field=models.IntegerField(default=99, verbose_name='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='participacaoencontro',
            name='coordenador',
            field=models.BooleanField(default=False, verbose_name='É Coordenador?'),
        ),
    ]
