# Generated by Django 5.2.16 on 2026-09-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_funcaoencontro_options_funcaoencontro_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpinista',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('pendente', 'pendente'), ('confirmado', 'confirmado'), ('inativo', 'inativo')], default='pendente', max_length=20),
        ),
    ]
