# Generated by Django 5.2.16 on 2026-09-07 19:30

import core.validators
from django.db import migrations, models


ABSENT_CPF_MARKERS = {'', 'false', 'none', 'null'}


def canonical_cpf_if_valid(value):
    value = str(value).strip()
    if len(value) == 14 and value[3] == '.' and value[7] == '.' and value[11] == '-':
        digits = value[:3] + value[4:7] + value[8:11] + value[12:]
    elif len(value) == 11:
        digits = value
    else:
        return None

    if not digits.isdigit() or len(set(digits)) == 1:
        return None

    for digit_index in (9, 10):
        weight = digit_index + 1
        total = sum(
            int(digit) * (weight - index)
            for index, digit in enumerate(digits[:digit_index])
        )
        remainder = (total * 10) % 11
        expected_digit = 0 if remainder == 10 else remainder
        if expected_digit != int(digits[digit_index]):
            return None

    return digits


def normalize_legacy_cpfs(apps, schema_editor):
    Alpinista = apps.get_model('core', 'Alpinista')
    changes = []
    canonical_owners = {}
    invalid_values_found = False

    for alpinista in Alpinista.objects.all().only('id', 'cpf').iterator():
        value = alpinista.cpf
        if value is None or str(value).strip().casefold() in ABSENT_CPF_MARKERS:
            changes.append((alpinista.id, None))
            continue

        canonical = canonical_cpf_if_valid(value)
        if canonical is None:
            invalid_values_found = True
            continue

        canonical_owners.setdefault(canonical, []).append(alpinista.id)
        if canonical != value:
            changes.append((alpinista.id, canonical))

    if invalid_values_found:
        raise RuntimeError(
            'A normalização de CPF encontrou valores legados não reconhecidos; '
            'nenhum dado foi alterado.'
        )

    collisions = {
        cpf: ids for cpf, ids in canonical_owners.items() if len(ids) > 1
    }
    if collisions:
        raise RuntimeError(
            'A normalização de CPF encontrou cadastros duplicados; '
            'nenhum dado foi alterado.'
        )

    for alpinista_id, cpf in changes:
        Alpinista.objects.filter(pk=alpinista_id).update(cpf=cpf)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_normalize_alpinista_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpinista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.RunPython(normalize_legacy_cpfs, migrations.RunPython.noop),
    ]
