# Generated by Django 5.2.16 on 2026-09-08 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fotoencontro_alter_alpinista_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nome', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_disponivel__gte', 0)), name='material_quantidade_nao_negativa')],
            },
        ),
        migrations.CreateModel(
            name='EntregaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('entregue_em', models.DateTimeField(auto_now_add=True)),
                ('alpinista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_materiais', to='core.alpinista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.material')),
            ],
            options={
                'ordering': ['-entregue_em', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='entrega_material_quantidade_positiva')],
            },
        ),
    ]
