# Generated by Django 5.2.16 on 2026-09-23 19:03

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_material_entregamaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, default='', max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', validators=[core.validators.validate_image_upload_size])),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('viuvo', 'Viúvo'), ('divorciado', 'Divorciado')], max_length=10, null=True)),
                ('batismo', models.BooleanField(blank=True, null=True)),
                ('primeira_comunhao', models.BooleanField(blank=True, null=True)),
                ('crisma', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAlpinista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violeiro', models.BooleanField(default=False)),
                ('canta', models.BooleanField(default=False)),
                ('disponivel_mme', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alpinista', to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='DadosSaudePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, default='')),
                ('intolerancias', models.TextField(blank=True, default='')),
                ('restricoes_alimentares', models.TextField(blank=True, default='')),
                ('neurodivergencia', models.TextField(blank=True, default='')),
                ('medicamentos', models.TextField(blank=True, default='')),
                ('condicao_medica', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_saude', to='core.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='alpinista',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alpinista_legado', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='EnderecoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('logradouro', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.pessoa')),
                ('regiao_administrativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='core.regiaoadministrativa')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('parentesco', models.CharField(blank=True, default='', max_length=100)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.BooleanField(default=False)),
                ('principal', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('whatsapp', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'numero'), name='telefone_unico_por_pessoa')],
            },
        ),
        migrations.CreateModel(
            name='VinculoConjugal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_pessoa_a', to='core.pessoa')),
                ('pessoa_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_pessoa_b', to='core.pessoa')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pessoa_a', models.F('pessoa_b')), _negated=True), name='vinculo_pessoas_distintas'), models.CheckConstraint(condition=models.Q(('pessoa_a__lt', models.F('pessoa_b'))), name='vinculo_ordem_canonica'), models.UniqueConstraint(fields=('pessoa_a', 'pessoa_b'), name='vinculo_conjugal_unico')],
            },
        ),
    ]
