# Generated by Django 5.2.16 on 2026-09-27 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_backfill_pessoa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('regiao_administrativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paroquias', to='core.regiaoadministrativa')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_alpinista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frequencias', to='core.perfilalpinista')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frequencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias', to='core.grupo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('perfil_alpinista', 'data'), name='frequencia_unica_perfil_data')],
            },
        ),
        migrations.CreateModel(
            name='CoordenacaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('jovem', 'Jovem'), ('adulto', 'Adulto')], max_length=10)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_alpinista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenacoes_grupo', to='core.perfilalpinista')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenacoes', to='core.grupo')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='coordenacao_grupo_periodo_valido'), models.UniqueConstraint(condition=models.Q(('fim__isnull', True)), fields=('perfil_alpinista',), name='coordenacao_grupo_atual_unica')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField()),
                ('vigente_ate', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('local_reuniao', models.CharField(blank=True, default='', max_length=255)),
                ('dia_semana', models.CharField(blank=True, default='', max_length=20)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.grupo')),
                ('paroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_grupo', to='core.paroquia')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('vigente_ate__isnull', True), ('vigente_ate__gte', models.F('vigente_desde')), _connector='OR'), name='config_grupo_periodo_valido'), models.UniqueConstraint(condition=models.Q(('vigente_ate__isnull', True)), fields=('grupo',), name='config_grupo_atual_unica')],
            },
        ),
        migrations.CreateModel(
            name='VinculoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='core.grupo')),
                ('perfil_alpinista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_grupo', to='core.perfilalpinista')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='vinculo_grupo_periodo_valido'), models.UniqueConstraint(condition=models.Q(('fim__isnull', True)), fields=('perfil_alpinista', 'grupo'), name='vinculo_grupo_atual_unico')],
            },
        ),
    ]
