# Generated by Django 5.2.16 on 2026-09-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_grupo_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontro',
            name='status',
            field=models.CharField(choices=[('em_agendamento', 'Em Agendamento'), ('agendado', 'Agendado'), ('em_preparacao', 'Em Preparação'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('adiado', 'Adiado'), ('cancelado', 'Cancelado')], default='em_agendamento', max_length=20),
        ),
        migrations.CreateModel(
            name='CalendarioEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('oficializado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('substituido_em', models.DateTimeField(blank=True, null=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='core.encontro')),
            ],
        ),
        migrations.CreateModel(
            name='DiaEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.calendarioencontro')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendarioencontro',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gt', 0)), name='calendario_encontro_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='calendarioencontro',
            constraint=models.UniqueConstraint(fields=('encontro', 'versao'), name='calendario_encontro_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='calendarioencontro',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('encontro',), name='calendario_encontro_vigente_unico'),
        ),
        migrations.AddConstraint(
            model_name='diaencontro',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gt', 0)), name='dia_encontro_ordem_positiva'),
        ),
        migrations.AddConstraint(
            model_name='diaencontro',
            constraint=models.UniqueConstraint(fields=('calendario', 'ordem'), name='dia_encontro_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='diaencontro',
            constraint=models.UniqueConstraint(fields=('calendario', 'data'), name='dia_encontro_data_unica'),
        ),
    ]
