# Generated by Django 5.2.16 on 2026-10-05 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_expand_inscricao_convite_participacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEquipeEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_encontro', models.CharField(choices=[('Escalada', 'Escalada'), ('AVC', 'AVC'), ('Esppa', 'Esppa'), ('Acampamento', 'Acampamento')], max_length=20)),
                ('codigo', models.SlugField()),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=99)),
                ('capacidade_minima_recomendada', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidade_maxima_recomendada', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo_encontro', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRoleEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=99)),
                ('quantidade_estrutural', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('concede_registro_presenca', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_equipe', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrabalhoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_alocacao', 'Aguardando alocação'), ('alocado', 'Alocado'), ('trabalhou', 'Trabalhou'), ('faltou', 'Faltou'), ('retirado', 'Retirado')], default='aguardando_alocacao', max_length=30)),
                ('resultado_registrado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=99)),
                ('capacidade_minima_recomendada', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidade_maxima_recomendada', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.encontro')),
            ],
            options={
                'ordering': ['encontro', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleEquipeEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=99)),
                ('quantidade_estrutural', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('concede_registro_presenca', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipe_encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='core.equipeencontro')),
            ],
            options={
                'ordering': ['equipe_encontro', 'ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conviteencontro',
            name='role_trabalho_proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_propostos', to='core.roleequipeencontro'),
        ),
        migrations.AddConstraint(
            model_name='conviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('finalidade', 'trabalhar'), ('role_trabalho_proposta__isnull', True), _connector='OR'), name='convite_role_apenas_trabalho'),
        ),
        migrations.AddIndex(
            model_name='templateequipeencontro',
            index=models.Index(fields=['tipo_encontro', 'ativo', 'ordem'], name='tmpl_eq_tipo_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateequipeencontro',
            constraint=models.UniqueConstraint(fields=('tipo_encontro', 'codigo'), name='template_equipe_codigo_unico_tipo'),
        ),
        migrations.AddConstraint(
            model_name='templateequipeencontro',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_encontro__in', ('Escalada', 'AVC', 'Esppa', 'Acampamento'))), name='template_equipe_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='templateequipeencontro',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade_minima_recomendada__isnull', True), ('capacidade_maxima_recomendada__isnull', True), ('capacidade_minima_recomendada__lte', models.F('capacidade_maxima_recomendada')), _connector='OR'), name='template_equipe_capacidade_coerente'),
        ),
        migrations.AddField(
            model_name='equipeencontro',
            name='template_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='core.templateequipeencontro'),
        ),
        migrations.AddField(
            model_name='templateroleequipe',
            name='template_equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='core.templateequipeencontro'),
        ),
        migrations.AddField(
            model_name='roleequipeencontro',
            name='template_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='core.templateroleequipe'),
        ),
        migrations.AddField(
            model_name='trabalhoencontro',
            name='convite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trabalho', to='core.conviteencontro'),
        ),
        migrations.AddField(
            model_name='trabalhoencontro',
            name='encontro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='core.encontro'),
        ),
        migrations.AddField(
            model_name='trabalhoencontro',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos_encontro', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='trabalhoencontro',
            name='role_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='core.roleequipeencontro'),
        ),
        migrations.AddIndex(
            model_name='equipeencontro',
            index=models.Index(fields=['encontro', 'ordem'], name='equipe_enc_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipeencontro',
            constraint=models.UniqueConstraint(fields=('encontro', 'codigo'), name='equipe_encontro_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='equipeencontro',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade_minima_recomendada__isnull', True), ('capacidade_maxima_recomendada__isnull', True), ('capacidade_minima_recomendada__lte', models.F('capacidade_maxima_recomendada')), _connector='OR'), name='equipe_encontro_capacidade_coerente'),
        ),
        migrations.AddIndex(
            model_name='templateroleequipe',
            index=models.Index(fields=['template_equipe', 'ativo', 'ordem'], name='tmpl_role_eq_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateroleequipe',
            constraint=models.UniqueConstraint(fields=('template_equipe', 'codigo'), name='template_role_codigo_unico_equipe'),
        ),
        migrations.AddConstraint(
            model_name='templateroleequipe',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_estrutural__isnull', True), ('quantidade_estrutural__gt', 0), _connector='OR'), name='template_role_quantidade_positiva'),
        ),
        migrations.AddIndex(
            model_name='roleequipeencontro',
            index=models.Index(fields=['equipe_encontro', 'ordem'], name='role_eq_enc_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleequipeencontro',
            constraint=models.UniqueConstraint(fields=('equipe_encontro', 'codigo'), name='role_equipe_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='roleequipeencontro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_estrutural__isnull', True), ('quantidade_estrutural__gt', 0), _connector='OR'), name='role_equipe_quantidade_positiva'),
        ),
        migrations.AddIndex(
            model_name='trabalhoencontro',
            index=models.Index(fields=['encontro', 'status'], name='trab_encontro_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trabalhoencontro',
            index=models.Index(fields=['pessoa', 'status'], name='trab_pessoa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trabalhoencontro',
            index=models.Index(fields=['role_equipe', 'status'], name='trab_role_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trabalhoencontro',
            constraint=models.UniqueConstraint(fields=('pessoa', 'encontro'), name='trabalho_unico_pessoa_encontro'),
        ),
        migrations.AddConstraint(
            model_name='trabalhoencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('aguardando_alocacao', 'alocado', 'trabalhou', 'faltou', 'retirado'))), name='trabalho_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='trabalhoencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role_equipe__isnull', True), ('status', 'aguardando_alocacao')), models.Q(('role_equipe__isnull', False), ('status__in', ('alocado', 'trabalhou', 'faltou'))), ('status', 'retirado'), _connector='OR'), name='trabalho_alocacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='trabalhoencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resultado_registrado_em__isnull', False), ('status__in', ('trabalhou', 'faltou'))), models.Q(('resultado_registrado_em__isnull', True), ('status__in', ('aguardando_alocacao', 'alocado', 'retirado'))), _connector='OR'), name='trabalho_resultado_coerente'),
        ),
    ]
