# Generated by Django 5.2.16 on 2026-10-05 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_expand_equipes_trabalho_encontro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoPreparatoriaEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reunioes_preparatorias', to='core.encontro')),
            ],
            options={
                'ordering': ['encontro', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PresencaPreparatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente_justificado', 'Ausente justificado'), ('ausente_sem_justificativa', 'Ausente sem justificativa')], max_length=30)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas_preparatorias_registradas', to=settings.AUTH_USER_MODEL)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas_preparatorias', to='core.trabalhoencontro')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='core.reuniaopreparatoriaencontro')),
            ],
            options={
                'ordering': ['reuniao', 'trabalho', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reuniaopreparatoriaencontro',
            index=models.Index(fields=['encontro', 'ordem'], name='reun_enc_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='reuniaopreparatoriaencontro',
            index=models.Index(fields=['encontro', 'data'], name='reun_enc_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='reuniaopreparatoriaencontro',
            constraint=models.UniqueConstraint(fields=('encontro', 'ordem'), name='reuniao_ordem_unica_encontro'),
        ),
        migrations.AddConstraint(
            model_name='reuniaopreparatoriaencontro',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gt', 0)), name='reuniao_ordem_positiva'),
        ),
        migrations.AddIndex(
            model_name='presencapreparatoria',
            index=models.Index(fields=['reuniao', 'status'], name='pres_reun_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='presencapreparatoria',
            constraint=models.UniqueConstraint(fields=('reuniao', 'trabalho'), name='presenca_unica_reuniao_trabalho'),
        ),
        migrations.AddConstraint(
            model_name='presencapreparatoria',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('presente', 'ausente_justificado', 'ausente_sem_justificativa'))), name='presenca_preparatoria_status_valido'),
        ),
    ]
