# Generated by Django 5.2.16 on 2026-10-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_expand_reunioes_presencas_preparatorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoUsuarioPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_usuario', to='core.pessoa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
