# Generated by Django 5.2.16 on 2026-10-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_vinculousuariopessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoFormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_codigo', models.SlugField(max_length=100)),
                ('tipo_conteudo', models.CharField(choices=[('palestra', 'Palestra'), ('bate_papo', 'Bate-papo')], max_length=20)),
                ('titulo_snapshot', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('realizada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_formativas', to='core.encontro')),
            ],
            options={
                'ordering': ['encontro', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PalestranteSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_externo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('ministrou', 'Ministrou'), ('nao_ministrou', 'Não ministrou')], default='previsto', max_length=20)),
                ('ministrou_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_alpinista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atuacoes_formativas', to='core.perfilalpinista')),
                ('sessao_formativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palestrantes', to='core.sessaoformativa')),
            ],
            options={
                'ordering': ['sessao_formativa', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sessaoformativa',
            index=models.Index(fields=['encontro', 'status'], name='sess_form_enc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoformativa',
            index=models.Index(fields=['tema_codigo', 'status'], name='sess_form_tema_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessaoformativa',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_conteudo__in', ('palestra', 'bate_papo'))), name='sessao_formativa_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='sessaoformativa',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('planejada', 'realizada', 'cancelada'))), name='sessao_formativa_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='sessaoformativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('realizada_em__isnull', False), ('status', 'realizada')), models.Q(('realizada_em__isnull', True), ('status__in', ('planejada', 'cancelada'))), _connector='OR'), name='sessao_formativa_realizacao_coerente'),
        ),
        migrations.AddIndex(
            model_name='palestrantesessao',
            index=models.Index(fields=['sessao_formativa', 'status'], name='pal_sessao_status_idx'),
        ),
        migrations.AddIndex(
            model_name='palestrantesessao',
            index=models.Index(fields=['perfil_alpinista', 'status'], name='pal_perfil_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='palestrantesessao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('previsto', 'ministrou', 'nao_ministrou'))), name='palestrante_sessao_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='palestrantesessao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('perfil_alpinista__isnull', False), ('nome_externo', '')), models.Q(('perfil_alpinista__isnull', True), models.Q(('nome_externo', ''), _negated=True)), _connector='OR'), name='palestrante_sessao_origem_xor'),
        ),
        migrations.AddConstraint(
            model_name='palestrantesessao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ministrou_em__isnull', False), ('status', 'ministrou')), models.Q(('ministrou_em__isnull', True), ('status__in', ('previsto', 'nao_ministrou'))), _connector='OR'), name='palestrante_sessao_atuacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='palestrantesessao',
            constraint=models.UniqueConstraint(condition=models.Q(('perfil_alpinista__isnull', False)), fields=('sessao_formativa', 'perfil_alpinista'), name='palestrante_alpinista_unico_sessao'),
        ),
    ]
