# Generated by Django 5.2.16 on 2026-10-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_expand_sessoes_formativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaVioleiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=20)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_violeiros', to='core.encontro')),
            ],
            options={
                'ordering': ['encontro', 'criada_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPropostaVioleiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_sugerido', models.CharField(choices=[('coordenador', 'Coordenador'), ('integrante', 'Integrante')], max_length=20)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('retirado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_alpinista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_propostas_violeiros', to='core.perfilalpinista')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.propostavioleiros')),
            ],
            options={
                'ordering': ['proposta', '-vigente', 'papel_sugerido', 'posicao', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='propostavioleiros',
            index=models.Index(fields=['encontro', 'status'], name='prop_vio_enc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='propostavioleiros',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('aberta', 'encerrada'))), name='proposta_violeiros_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='propostavioleiros',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encerrada_em__isnull', True), ('status', 'aberta')), models.Q(('encerrada_em__isnull', False), ('status', 'encerrada')), _connector='OR'), name='proposta_violeiros_encerramento_coerente'),
        ),
        migrations.AddIndex(
            model_name='itempropostavioleiros',
            index=models.Index(fields=['proposta', 'vigente', 'papel_sugerido', 'posicao'], name='item_prop_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='itempropostavioleiros',
            index=models.Index(fields=['perfil_alpinista', 'vigente'], name='item_prop_perfil_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempropostavioleiros',
            constraint=models.CheckConstraint(condition=models.Q(('papel_sugerido__in', ('coordenador', 'integrante'))), name='item_proposta_papel_valido'),
        ),
        migrations.AddConstraint(
            model_name='itempropostavioleiros',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('papel_sugerido', 'coordenador'), ('posicao', 1)), models.Q(('papel_sugerido', 'integrante'), ('posicao__gte', 1), ('posicao__lte', 4)), _connector='OR'), name='item_proposta_slot_valido'),
        ),
        migrations.AddConstraint(
            model_name='itempropostavioleiros',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retirado_em__isnull', True), ('vigente', True)), models.Q(('retirado_em__isnull', False), ('vigente', False)), _connector='OR'), name='item_proposta_vigencia_coerente'),
        ),
        migrations.AddConstraint(
            model_name='itempropostavioleiros',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('proposta', 'papel_sugerido', 'posicao'), name='item_proposta_slot_vigente_unico'),
        ),
        migrations.AddConstraint(
            model_name='itempropostavioleiros',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('proposta', 'perfil_alpinista'), name='item_proposta_perfil_vigente_unico'),
        ),
    ]
