# Generated by Django 5.2 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_diaencontro_data_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaencontro',
            name='rotulo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reuniaopreparatoriaencontro',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AvaliacaoEncontro',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                (
                    'encontro',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='avaliacao_agenda',
                        to='core.encontro',
                    ),
                ),
            ],
            options={
                'ordering': ['data', 'id'],
                'indexes': [
                    models.Index(
                        fields=['data'],
                        name='aval_encontro_data_idx',
                    ),
                ],
            },
        ),
    ]
