# Generated by Django 5.2.16 on 2026-10-07 12:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_expand_agenda_encontro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoCalendarioInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('PUBLICO', 'Público'), ('INTERNO', 'Interno')], max_length=10)),
                ('periodo', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=10)),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('arquivo_pdf', models.FileField(max_length=255, upload_to=core.models.calendario_publicacao_upload_to)),
                ('sha256', models.CharField(max_length=64)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes_calendario_institucional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publicado_em', '-id'],
                'indexes': [models.Index(fields=['periodo', 'ano', 'mes', 'publicado_em'], name='pub_cal_periodo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('escopo__in', ['PUBLICO', 'INTERNO'])), name='pub_cal_escopo_valido'), models.CheckConstraint(condition=models.Q(models.Q(('mes__gte', 1), ('mes__lte', 12), ('periodo', 'MENSAL')), models.Q(('mes__isnull', True), ('periodo', 'ANUAL')), _connector='OR'), name='pub_cal_periodo_mes_coerente')],
            },
        ),
    ]
