# Generated by Django 5.2.16 on 2026-10-07 13:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_publicacao_calendario_institucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaocalendarioinstitucional',
            name='layout',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL_RESUMIDO', 'Anual resumido')], default='MENSAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacaocalendarioinstitucional',
            name='periodo',
            field=models.CharField(choices=[('MENSAL', 'Mês'), ('ANUAL', 'Ano')], max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacaocalendarioinstitucional',
            name='publicado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='publicacaocalendarioinstitucional',
            index=models.Index(fields=['periodo', 'layout', 'ano', 'mes', 'publicado_em'], name='pub_cal_layout_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicacaocalendarioinstitucional',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('layout', 'MENSAL'), ('periodo', 'MENSAL')), models.Q(('layout__in', ['MENSAL', 'ANUAL_RESUMIDO']), ('periodo', 'ANUAL')), _connector='OR'), name='pub_cal_periodo_layout_valido'),
        ),
    ]
