# Generated by Django 5.2.16 on 2026-10-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_calendario_publicacao_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoriaEncontro',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('fato', models.CharField(max_length=100)),
                ('entidade', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('valor_anterior', models.JSONField(default=dict)),
                ('valor_novo', models.JSONField(default=dict)),
                ('justificativa', models.TextField(blank=True, default='')),
                (
                    'criado_em',
                    models.DateTimeField(auto_now_add=True, editable=False),
                ),
                (
                    'ator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='eventos_auditoria_encontro',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'encontro',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='eventos_auditoria',
                        to='core.encontro',
                    ),
                ),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [
                    models.Index(
                        fields=['encontro', 'criado_em'],
                        name='aud_enc_data_idx',
                    ),
                    models.Index(
                        fields=['entidade', 'objeto_id', 'criado_em'],
                        name='aud_objeto_data_idx',
                    ),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('fato', ''), _negated=True),
                        name='aud_fato_nao_vazio',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('entidade', ''), _negated=True),
                        name='aud_entidade_nao_vazia',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('objeto_id', ''), _negated=True),
                        name='aud_objeto_id_nao_vazio',
                    ),
                ],
            },
        ),
    ]
