# Generated by Django 5.2.16 on 2026-10-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_eventoauditoriaencontro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEncontristasEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.PositiveIntegerField()),
                ('idade_minima', models.PositiveSmallIntegerField()),
                ('idade_maxima', models.PositiveSmallIntegerField()),
                ('inscricoes_abrem_em', models.DateTimeField()),
                ('inscricoes_encerram_em', models.DateTimeField()),
                ('encontro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_encontristas', to='core.encontro')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidade__gt', 0)), name='cfg_encontr_cap_positiva'), models.CheckConstraint(condition=models.Q(('idade_minima__lte', models.F('idade_maxima'))), name='cfg_encontr_idades_coerentes'), models.CheckConstraint(condition=models.Q(('inscricoes_abrem_em__lt', models.F('inscricoes_encerram_em'))), name='cfg_encontr_janela_coerente')],
            },
        ),
    ]
