# Generated by Django 5.2.16 on 2026-10-09 01:28

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_configuracaoencontristasencontro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(choices=[('publica', 'Pública'), ('administrativa', 'Administrativa')], max_length=20)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='enviada', max_length=20)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('reativada_em', models.DateTimeField(blank=True, null=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_encontristas', to='core.encontro')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_por_encontro', to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEsppaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('viuvo', 'Viúvo'), ('divorciado', 'Divorciado')], max_length=20)),
                ('nome_conjuge', models.CharField(blank=True, default='', max_length=255)),
                ('telefone_conjuge', models.CharField(blank=True, default='', max_length=20)),
                ('nome_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('relacao_referencia', models.CharField(blank=True, choices=[('pai_mae', 'Pai ou mãe'), ('irmao_irma', 'Irmão ou irmã'), ('outro_familiar', 'Outro familiar'), ('amigo', 'Amigo(a)'), ('outro', 'Outro')], default='', max_length=30)),
                ('telefone_referencia', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_esppa', to='core.inscricaoencontro')),
            ],
        ),
        migrations.CreateModel(
            name='DadosDeclaradosInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, default='', max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, validators=[core.validators.validate_cpf])),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('como_conheceu', models.CharField(choices=[('indicacao', 'Indicação de amigo ou familiar'), ('paroquia', 'Paróquia'), ('redes_sociais', 'Redes sociais'), ('ja_conhecia', 'Já conhecia o Movimento Escalada'), ('outro', 'Outro')], max_length=30)),
                ('como_conheceu_outro', models.CharField(blank=True, default='', max_length=255)),
                ('batismo', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('primeira_comunhao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('crisma', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot_atual', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_declarados', to='core.inscricaoencontro')),
            ],
        ),
        migrations.CreateModel(
            name='DadosCuidadoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_alergias', models.CharField(blank=True, choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=3, null=True)),
                ('alergias', models.TextField(blank=True, default='')),
                ('possui_restricoes_intolerancias', models.CharField(blank=True, choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=3, null=True)),
                ('restricoes_intolerancias', models.TextField(blank=True, default='')),
                ('usa_medicamentos', models.CharField(blank=True, choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=3, null=True)),
                ('medicamentos', models.TextField(blank=True, default='')),
                ('horarios_medicamentos', models.TextField(blank=True, default='')),
                ('observacoes_medicamentos', models.TextField(blank=True, default='')),
                ('neurodivergencia_apoio', models.CharField(blank=True, choices=[('nao', 'Não'), ('sim', 'Sim'), ('prefere_nao_informar', 'Prefere não informar')], max_length=25, null=True)),
                ('neurodivergencia_condicao', models.TextField(blank=True, default='')),
                ('necessidades_apoio', models.TextField(blank=True, default='')),
                ('sensibilidades_desconfortos', models.TextField(blank=True, default='')),
                ('o_que_ajuda', models.TextField(blank=True, default='')),
                ('outras_informacoes', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_cuidado', to='core.inscricaoencontro')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaCadastralInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_sinal', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('sugerida', 'Sugerida'), ('rejeitada', 'Rejeitada'), ('aceita', 'Aceita')], default='sugerida', max_length=20)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias_cadastrais_decididas', to=settings.AUTH_USER_MODEL)),
                ('pessoa_candidata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias_inscricao', to='core.pessoa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencias_cadastrais', to='core.inscricaoencontro')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelDeclaradoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, validators=[core.validators.validate_cpf])),
                ('parentesco', models.CharField(max_length=100)),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_declarado', to='core.inscricaoencontro')),
            ],
        ),
        migrations.AddIndex(
            model_name='inscricaoencontro',
            index=models.Index(fields=['encontro', 'status', 'origem'], name='insc_enc_status_origem_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricaoencontro',
            index=models.Index(fields=['pessoa', 'encontro'], name='insc_pessoa_encontro_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricaoencontro',
            index=models.Index(fields=['enviada_em'], name='insc_enviada_em_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoencontro',
            constraint=models.UniqueConstraint(condition=models.Q(('pessoa__isnull', False)), fields=('encontro', 'pessoa'), name='insc_encontro_pessoa_unica'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('enviada', 'cancelada'))), name='insc_encontro_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoencontro',
            constraint=models.CheckConstraint(condition=models.Q(('origem__in', ('publica', 'administrativa'))), name='insc_encontro_origem_valida'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelada'), _negated=True), ('cancelada_em__isnull', False), _connector='OR'), name='insc_cancelamento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='dadosesppainscricao',
            constraint=models.CheckConstraint(condition=models.Q(('estado_civil__in', ('solteiro', 'casado', 'viuvo', 'divorciado'))), name='dados_esppa_estado_civil_valido'),
        ),
        migrations.AddConstraint(
            model_name='dadosesppainscricao',
            constraint=models.CheckConstraint(condition=models.Q(('relacao_referencia', ''), ('relacao_referencia__in', ('pai_mae', 'irmao_irma', 'outro_familiar', 'amigo', 'outro')), _connector='OR'), name='dados_esppa_relacao_valida'),
        ),
        migrations.AddIndex(
            model_name='dadosdeclaradosinscricao',
            index=models.Index(fields=['cpf'], name='dados_insc_cpf_idx'),
        ),
        migrations.AddConstraint(
            model_name='dadosdeclaradosinscricao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('telefone_whatsapp', ''), _negated=True), _connector='OR'), name='dados_insc_contato_presente'),
        ),
        migrations.AddConstraint(
            model_name='dadosdeclaradosinscricao',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__gt', 0)), name='dados_insc_schema_positivo'),
        ),
        migrations.AddConstraint(
            model_name='dadosdeclaradosinscricao',
            constraint=models.CheckConstraint(condition=models.Q(('como_conheceu__in', ('indicacao', 'paroquia', 'redes_sociais', 'ja_conhecia', 'outro'))), name='dados_insc_origem_valida'),
        ),
        migrations.AddConstraint(
            model_name='dadosdeclaradosinscricao',
            constraint=models.CheckConstraint(condition=models.Q(('batismo__in', ('sim', 'nao', 'nao_sei', 'nao_informado')), ('primeira_comunhao__in', ('sim', 'nao', 'nao_sei', 'nao_informado')), ('crisma__in', ('sim', 'nao', 'nao_sei', 'nao_informado'))), name='dados_insc_sacramentos_validos'),
        ),
        migrations.AddConstraint(
            model_name='dadoscuidadoinscricao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('possui_alergias__isnull', True), ('possui_alergias__in', ('nao', 'sim')), _connector='OR'), models.Q(('possui_restricoes_intolerancias__isnull', True), ('possui_restricoes_intolerancias__in', ('nao', 'sim')), _connector='OR'), models.Q(('usa_medicamentos__isnull', True), ('usa_medicamentos__in', ('nao', 'sim')), _connector='OR'), models.Q(('neurodivergencia_apoio__isnull', True), ('neurodivergencia_apoio__in', ('nao', 'sim', 'prefere_nao_informar')), _connector='OR')), name='dados_cuidado_respostas_validas'),
        ),
        migrations.AddConstraint(
            model_name='correspondenciacadastralinscricao',
            constraint=models.UniqueConstraint(fields=('inscricao', 'pessoa_candidata'), name='corresp_insc_pessoa_unica'),
        ),
        migrations.AddConstraint(
            model_name='correspondenciacadastralinscricao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aceita')), fields=('inscricao',), name='corresp_insc_aceita_unica'),
        ),
        migrations.AddConstraint(
            model_name='correspondenciacadastralinscricao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('sugerida', 'rejeitada', 'aceita'))), name='corresp_insc_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='correspondenciacadastralinscricao',
            constraint=models.CheckConstraint(condition=models.Q(('origem_sinal', ''), _negated=True), name='corresp_insc_origem_nao_vazia'),
        ),
        migrations.AddConstraint(
            model_name='correspondenciacadastralinscricao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decidida_em__isnull', True), ('decidida_por__isnull', True), ('status', 'sugerida')), models.Q(('decidida_em__isnull', False), ('decidida_por__isnull', False), ('status__in', ('rejeitada', 'aceita'))), _connector='OR'), name='corresp_insc_decisao_coerente'),
        ),
    ]
