# Generated by Django 5.2.16 on 2026-10-09 18:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_configuracaoencontristasencontro_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaConvitesEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('aguardando_decisao', 'Aguardando decisão'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_confirmacao', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='campanha_convites', to='core.encontro')),
                ('iniciada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_convites_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadeConviteEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use um digest SHA-256 hexadecimal em minúsculas.', regex='^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('consumida', 'Consumida'), ('invalidada', 'Invalidada'), ('expirada', 'Expirada'), ('suspensa', 'Suspensa')], default='pendente', max_length=20)),
                ('expira_em', models.DateTimeField()),
                ('consumida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('convite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='core.conviteencontro')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaConviteEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('entregue', 'Entregue'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('chave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('primeira_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('codigo_erro', models.CharField(blank=True, default='', max_length=100)),
                ('erro_tecnico', models.CharField(blank=True, default='', max_length=500)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.oportunidadeconviteencontro')),
            ],
        ),
        migrations.CreateModel(
            name='RodadaConvitesEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('reposicao', 'Reposição'), ('prorrogacao', 'Prorrogação')], max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=20)),
                ('aberta_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rodadas', to='core.campanhaconvitesencontro')),
            ],
            options={
                'ordering': ['campanha_id', 'sequencia'],
            },
        ),
        migrations.AddField(
            model_name='oportunidadeconviteencontro',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='core.rodadaconvitesencontro'),
        ),
        migrations.AddIndex(
            model_name='campanhaconvitesencontro',
            index=models.Index(fields=['status', 'prazo_confirmacao'], name='camp_conv_status_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='campanhaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ativa', 'aguardando_decisao', 'encerrada'))), name='camp_conv_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='campanhaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('prazo_confirmacao__gt', models.F('iniciada_em'))), name='camp_conv_prazo_coerente'),
        ),
        migrations.AddConstraint(
            model_name='campanhaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encerrada_em__isnull', False), ('status', 'encerrada')), models.Q(models.Q(('status', 'encerrada'), _negated=True), ('encerrada_em__isnull', True)), _connector='OR'), name='camp_conv_encerramento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='campanhaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('encerrada_em__isnull', True), ('encerrada_em__gte', models.F('iniciada_em')), _connector='OR'), name='camp_conv_datas_coerentes'),
        ),
        migrations.AddIndex(
            model_name='entregaconviteencontro',
            index=models.Index(fields=['oportunidade', 'status'], name='ent_conv_op_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaconviteencontro',
            index=models.Index(fields=['status', 'proxima_tentativa_em'], name='ent_conv_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.UniqueConstraint(fields=('oportunidade', 'canal'), name='ent_conv_op_canal_unica'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('canal__in', ('email', 'whatsapp'))), name='ent_conv_canal_valido'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pendente', 'enviando', 'entregue', 'falhou'))), name='ent_conv_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('primeira_tentativa_em__isnull', True), ('tentativas', 0), ('ultima_tentativa_em__isnull', True)), models.Q(('primeira_tentativa_em__isnull', False), ('tentativas__gt', 0), ('ultima_tentativa_em__isnull', False)), _connector='OR'), name='ent_conv_tentativas_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('ultima_tentativa_em__isnull', True), ('ultima_tentativa_em__gte', models.F('primeira_tentativa_em')), _connector='OR'), name='ent_conv_tentativas_ordem'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entregue_em__isnull', False), ('status', 'entregue'), ('tentativas__gt', 0)), models.Q(models.Q(('status', 'entregue'), _negated=True), ('entregue_em__isnull', True)), _connector='OR'), name='ent_conv_entrega_coerente'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('primeira_tentativa_em__isnull', True), ('primeira_tentativa_em__gte', models.F('criada_em')), _connector='OR'), name='ent_conv_primeira_tentativa_ordem'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('entregue_em__isnull', True), ('entregue_em__gte', models.F('primeira_tentativa_em')), _connector='OR'), name='ent_conv_entrega_ordem'),
        ),
        migrations.AddConstraint(
            model_name='entregaconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('proxima_tentativa_em__isnull', True), models.Q(('proxima_tentativa_em__gte', models.F('ultima_tentativa_em')), ('tentativas__gt', 0), ('ultima_tentativa_em__isnull', False)), _connector='OR'), name='ent_conv_retry_ordem'),
        ),
        migrations.AddIndex(
            model_name='rodadaconvitesencontro',
            index=models.Index(fields=['campanha', 'status', 'aberta_em'], name='rod_conv_camp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.UniqueConstraint(fields=('campanha', 'sequencia'), name='rod_conv_camp_sequencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('sequencia__gt', 0)), name='rod_conv_sequencia_positiva'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ('inicial', 'reposicao', 'prorrogacao'))), name='rod_conv_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('aberta', 'encerrada'))), name='rod_conv_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encerrada_em__isnull', False), ('status', 'encerrada')), models.Q(('status', 'aberta'), ('encerrada_em__isnull', True)), _connector='OR'), name='rod_conv_encerramento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='rodadaconvitesencontro',
            constraint=models.CheckConstraint(condition=models.Q(('encerrada_em__isnull', True), ('encerrada_em__gte', models.F('aberta_em')), _connector='OR'), name='rod_conv_datas_coerentes'),
        ),
        migrations.AddIndex(
            model_name='oportunidadeconviteencontro',
            index=models.Index(fields=['rodada', 'status'], name='op_conv_rod_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.UniqueConstraint(fields=('rodada', 'convite'), name='op_conv_rod_convite_unica'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pendente', 'consumida', 'invalidada', 'expirada', 'suspensa'))), name='op_conv_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('token_digest__regex', '^[0-9a-f]{64}$')), name='op_conv_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('expira_em__gt', models.F('criada_em'))), name='op_conv_expiracao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumida_em__isnull', False), ('status', 'consumida')), models.Q(models.Q(('status', 'consumida'), _negated=True), ('consumida_em__isnull', True)), _connector='OR'), name='op_conv_consumo_coerente'),
        ),
        migrations.AddConstraint(
            model_name='oportunidadeconviteencontro',
            constraint=models.CheckConstraint(condition=models.Q(('consumida_em__isnull', True), models.Q(('consumida_em__gte', models.F('criada_em')), ('consumida_em__lte', models.F('expira_em'))), _connector='OR'), name='op_conv_consumo_no_prazo'),
        ),
    ]
