# Generated by Django 5.2.16 on 2026-10-10 16:43

import core.models
import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_expand_outbox_e_sinal_reposicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoPreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_informado', models.CharField(blank=True, default='', max_length=255)),
                ('data_nascimento_informada', models.DateField(blank=True, null=True)),
                ('cpf_informado', models.CharField(blank=True, max_length=14, null=True, validators=[core.validators.validate_cpf])),
                ('telefone_informado', models.CharField(blank=True, default='', max_length=20)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_pre_encontro', to='core.inscricaoencontro')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_pre_encontro', to='core.pessoa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_pre_encontro_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoTemporariaPreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(max_length=255, upload_to=core.models.foto_pre_encontro_upload_to, validators=[core.validators.validate_image_upload_size])),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='foto_privada', to='core.atendimentopreencontro')),
            ],
        ),
        migrations.CreateModel(
            name='PreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encontro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pre_encontro', to='core.encontro')),
            ],
        ),
        migrations.AddField(
            model_name='atendimentopreencontro',
            name='pre_encontro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.preencontro'),
        ),
        migrations.CreateModel(
            name='DecisaoVagaPreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_decisao_diretoria', 'Aguardando decisão da Diretoria'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado')], default='aguardando_decisao_diretoria', max_length=30)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decisao_vaga', to='core.atendimentopreencontro')),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisoes_vaga_pre_encontro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('aguardando_decisao_diretoria', 'aprovado', 'nao_aprovado'))), name='dec_vaga_pre_status_valido'), models.CheckConstraint(condition=models.Q(models.Q(('decidida_em__isnull', True), ('decidida_por__isnull', True), ('status', 'aguardando_decisao_diretoria')), models.Q(('decidida_em__isnull', False), ('decidida_por__isnull', False), ('status__in', ('aprovado', 'nao_aprovado'))), _connector='OR'), name='dec_vaga_pre_decisao_coerente')],
            },
        ),
        migrations.CreateModel(
            name='PagamentoPreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('isento', 'Isento')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forma', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], default='', max_length=20)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='core.atendimentopreencontro')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pendente', 'pago', 'isento'))), name='pag_pre_status_valido'), models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='pag_pre_valor_nao_negativo'), models.CheckConstraint(condition=models.Q(('forma', ''), ('forma__in', ('pix', 'dinheiro', 'cartao', 'outro')), _connector='OR'), name='pag_pre_forma_valida')],
            },
        ),
        migrations.AddIndex(
            model_name='atendimentopreencontro',
            index=models.Index(fields=['pre_encontro', 'registrado_em'], name='atend_pre_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='atendimentopreencontro',
            constraint=models.CheckConstraint(condition=models.Q(('inscricao__isnull', False), ('pessoa__isnull', False), models.Q(models.Q(('nome_informado', ''), _negated=True), ('data_nascimento_informada__isnull', False), models.Q(('telefone_informado', ''), _negated=True)), _connector='OR'), name='atend_pre_origem_valida'),
        ),
        migrations.AddConstraint(
            model_name='atendimentopreencontro',
            constraint=models.UniqueConstraint(condition=models.Q(('inscricao__isnull', False)), fields=('pre_encontro', 'inscricao'), name='atend_pre_inscricao_unica'),
        ),
        migrations.AddConstraint(
            model_name='atendimentopreencontro',
            constraint=models.UniqueConstraint(condition=models.Q(('pessoa__isnull', False)), fields=('pre_encontro', 'pessoa'), name='atend_pre_pessoa_unica'),
        ),
        migrations.AddConstraint(
            model_name='atendimentopreencontro',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_informado__isnull', False), models.Q(('cpf_informado', ''), _negated=True)), fields=('pre_encontro', 'cpf_informado'), name='atend_pre_cpf_unico'),
        ),
        migrations.AddConstraint(
            model_name='atendimentopreencontro',
            constraint=models.CheckConstraint(condition=models.Q(('cpf_informado__isnull', True), ('cpf_informado', ''), ('cpf_informado__regex', '^\\d{11}$'), _connector='OR'), name='atend_pre_cpf_canonico'),
        ),
    ]
