# Generated by Django 5.2.16 on 2026-10-10 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_atendimentopreencontro_fototemporariapreencontro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaCuidadoPreEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('dados_cuidado_atualizado_em', models.DateTimeField()),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conferencia_cuidado', to='core.atendimentopreencontro')),
                ('conferido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_cuidado_pre_encontro', to=settings.AUTH_USER_MODEL)),
                ('dados_cuidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_pre_encontro', to='core.dadoscuidadoinscricao')),
            ],
        ),
    ]
